session4/config/routes.rb
Session3::Application.routes.draw do

  resources :articles
  root :to => "articles#index"
  

  match ':controller(/:action(/:id(.:format)))'
end

session4/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comment, :dependent => :destroy
  
  scope :rating_is_or_above, lambda {|rating| where("rating > ?", rating)}
  
  validates :title, :presence => true,
                    :uniqueness => true
end

session4/app/models/categories_product.rb
class CategoriesProduct < ActiveRecord::Base
end

session4/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :product
end

session4/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

session4/app/models/country.rb
class Countries < ActiveRecord::Base
  belongs_to :users
  
  validates :code, :presence => true,
                   
  validates :name, :presence => true,
                   :length => {:minimum => 1, :maximum => 15}
  
  validate :valid_code
  def valid_code
   self.errors[:code] << "only filled id,usa,frc" if (code != "id" && code != "usa" && code!= "frc")
  end  

end

session4/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :category
  
  scope :price_more_than_1000, where('price > 1000')
    
end

session4/app/models/user.rb
class Users < ActiveRecord::Base
  has_many :article, :dependent => :destroy
  has_many :product, :dependent => :destroy
  has_one :country
  has_many :my_country_article, 
           :class_name => "article", 
           :foreign_key => "user_id",
           :conditions => "title like '%my country%'"
           
  
  validates :first_name, :presence => true,
                         :uniqueness => true,
                         :length => {:minimum => 1, :maximum => 20},
                         :format => {:with => /[a-zA-Z\s]+$/}
  validates :last_name,  :presence => true,
                         :uniqueness => true,
                         :length => {:minimum => 1, :maximum => 20},
                         :format => {:with => /[a-zA-Z\s]+$/}
  validates :email, :presence => true,
                    :uniqueness => true
                      
  def full_address
    #self disini adalah object yang memanggil method tersebut.
    "#{self.address} #{self.last_name}"
  end
  
  
end 

session4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

session4/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def welcome
    render :text => "Welcome to Ruby on Rails"
  end
  def new
    @article = Article.new  
  end
  def index
    @article = Article.all
  end
  def edit
    @article = Article.find(params[:id])
  end
  def update
     @article = Article.find(params[:id])
     if @article.update_attributes(params[:article])
     redirect_to articles_path, :notice => 'Article was successfully updated.'
   else
     flash[:error] = 'Article was failed to update.'
     render :action => 'edit'
   end
  end
  def create
    @article= Article.new(params[:article])
    if @article.save
      flash[:notice] = "Article successfully saved"
      redirect_to :action => :index
    else
      flash.now[:notice] = "Article failed to saved"
      render :action => :new
    end
  end
  
  def destroy
    Article.destroy(params[:id])
    redirect_to articles_path, :notice => 'Article was successfully deleted'
  end
  
  def show
  @articles = Article.find(params[:id])
  respond_to do |format|
    format.html  # show.html.erb
    format.json  { render :json => @articles }
  end
end

end

session4/app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end

  def say_hello
    render :text => "<h1>Hello World</h1>"
  end
  
  def say
    @hello = "Hello World"
  end
end

session4/app/controllers/say_controller.rb
class SayController < ApplicationController
def hello
end
def goodbye
end
end

session4/app/helpers/application_helper.rb
module ApplicationHelper
end

session4/app/helpers/articles_helper.rb
module ArticlesHelper
end

session4/app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<table>
<%= form_for @article do |article| %>
  <tr>
    <td><%= article.label :title %></td>
    <td><%= article.text_field :title %></td>
  </tr>
  <tr>
    <td><%= article.label :body %></td>
    <td><%= article.text_area :body %></td>
  </tr>
  <tr>
    <td><%= article.submit %></td>
  </tr>
<% end %>
</table>

session4/app/views/articles/index.html.erb
<h1>List Of Articles</h1>
<%= flash[:notice] %>
<table>
  <tr>
    <td>Title</td>
    <td>Content</td>
    <td>Option</td>
  </tr>
  <% @article.each do |article|%>
  <tr>
  <td><%= article.title %></td>
  <td><%= article.body %></td>
  <td><%= link_to 'Edit', edit_article_path(article.id) %> | <%= link_to 'Delete', article_path(article.id), :confirm => 'Are you sure want to delete?', :method => :delete %>
  </tr>
  <% end %>
</table>

<p><%= link_to "Add new Article", new_article_path%></p>

session4/app/views/articles/new.html.erb
<h1>New Article</h1>
<%= flash[:notice] %>
<table>
<%= form_for @article do |article| %>
  <tr>
    <td><%= article.label :title %></td>
    <td><%= article.text_field :title %></td>
  </tr>
  <tr>
    <td><%= article.label :body %></td>
    <td><%= article.text_area :body %></td>
  </tr>
  <tr>
    <td><%= article.submit %></td>
  </tr>
<% end %>
</table>
<%= link_to 'Back to Articles', articles_path %>

session4/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  <b>Name:</b>
  <%= @Articles.id %>
</p>
 
<p>
  <b>Title:</b>
  <%= @Articles.title %>
</p>
 
<p>
  <b>Content:</b>
  <%= @Articles.body %>
</p>
 
 
<%= link_to 'Edit', edit_Articles_path(@Articles) %> |
<%= link_to 'Back', Articles_path %>

session4/app/views/hello/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>test1</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<h1>Hello World</h1>

<h2><%= @hello %></h2>

</body>
</html>

session4/app/views/hello/say.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>test1</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<h2><%= @hello %></h2>

</body>
</html>

session4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Session4</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

session4/app/views/say/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hello, Rails!</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Hello from Rails!</h1>
</body>
</html>